name: auto-assign-to-author
on:
    pull_request_target:
        types: [opened, reopened]

permissions:
    pull-requests: write

jobs:
    auto-assign-to-author:
        runs-on: ubuntu-latest
        container: node:20
        steps:
            # - uses: actions/checkout@v4
            - run: npm install @actions/core
            - run: npm install @actions/github
            - run: node .github/workflows/src/index.js ${{ github.token }}