name: auto-assign-to-author
on:
    pull_request_target:
        types: [opened, ready_for_review]

permissions:
    pull-requests: write

jobs:
    auto-assign-to-author:
        runs-on: ubuntu-latest
        steps:
            - uses: ./actions/auto-assign
              with:
                  repo-token: ${{ github.token }}